@extends('be.master')
@section('menu')@include('be.menu')@endsection
@section('user')
<nav class="navbar navbar-main navbar-expand-lg px-0 mx-4 shadow-none border-radius-xl"><div class="container-fluid py-1 px-3"><nav aria-label="breadcrumb"><ol class="breadcrumb bg-transparent mb-0 pb-0 pt-1 px-0"><li class="breadcrumb-item text-sm"><a class="opacity-5 text-dark" href="#">Pages</a></li><li class="breadcrumb-item text-sm text-dark active">{{ $title }}</li></ol><h6 class="font-weight-bolder mb-0">{{ $title }}</h6></nav><div class="collapse navbar-collapse"><div class="ms-md-auto pe-md-3"></div><ul class="navbar-nav justify-content-end"><li class="nav-item"><div class="mx-3"><a href="{{route('user.create')}}" class="btn btn-primary btn-sm mb-0">Add New {{ $title }}</a></div></li></ul></div></div></nav>
<div class="container-fluid py-4"><div class="row"><div class="col-12"><div class="card mb-4"><div class="card-header pb-0"><h6>{{$title}} Data</h6></div>
<div class="card-body px-0 pt-0 pb-2"><div class="table-responsive p-0"><table class="table align-items-center mb-0">
<thead><tr><th class="text-uppercase text-primary text-xs font-weight-bolder opacity-7">No</th><th class="text-uppercase text-primary text-xs font-weight-bolder opacity-7">Name</th><th class="text-uppercase text-primary text-xs font-weight-bolder opacity-7">Email</th><th class="text-uppercase text-primary text-xs font-weight-bolder opacity-7">Aksi</th></tr></thead>
<tbody>@foreach ($datas as $nmr => $data)<tr><td class="text-xs text-secondary ps-4">{{$nmr + 1}}</td><td class="text-xs text-secondary ps-4">{{$data->name}}</td><td class="text-xs text-secondary ps-4">{{$data->email}}</td><td class="text-xs text-secondary ps-4"><a href="{{ route('user.edit', $data->id) }}"><img src="{{asset('be/assets/img/icons/edit.png')}}" alt="" width="20"></a><form action="{{ route('user.destroy', $data->id) }}" method="POST" style="display:inline;">@csrf @method('DELETE')<button type="submit" style="border:none;background:none;"><img src="{{asset('be/assets/img/icons/delete.png')}}" alt="" width="20"></button></form></td></tr>@endforeach</tbody>
</table></div></div></div></div></div></div>
<script>@if(session('simpan'))swal("Success","{{session('simpan')}}","success");@endif @if(session('ubah'))swal("Success","{{session('ubah')}}","success");@endif @if(session('hapus'))swal("Deleted","{{session('hapus')}}","success");@endif</script>
@endsection
